/* Rare — Other Side Collection data.
   Platform links + 10 rare videos (real YouTube links) + Wikipedia pages & images. */
window.RARE_COLLECTION = {
  platforms: [
    { key: "youtube", name: "YouTube", icon: "\u25B6", color: "#ff0000", internal: true,
      href: "youtube.html", desc: "10 rare videos and footage \u2014 by link." },
    { key: "wikipedia", name: "Wikipedia", icon: "W", color: "#111827", internal: true,
      href: "wikipedia.html", desc: "Rare pages and images from the free encyclopedia." },
    { key: "instagram", name: "Instagram", icon: "\u25C9", color: "#e1306c", external: true,
      href: "https://www.instagram.com/explore/search/keyword/?q=rare%20archive",
      desc: "Rare photos and reels shared on Instagram." },
    { key: "facebook", name: "Facebook", icon: "f", color: "#1877f2", external: true,
      href: "https://www.facebook.com/search/top?q=rare%20archive",
      desc: "Rare finds and groups across Facebook." },
    { key: "x", name: "X (Twitter)", icon: "\u{1D54F}", color: "#111111", external: true,
      href: "https://twitter.com/search?q=rare%20footage",
      desc: "Rare clips and threads on X." },
    { key: "reddit", name: "Reddit", icon: "r", color: "#ff4500", external: true,
      href: "https://www.reddit.com/search/?q=rare+footage",
      desc: "Communities hunting rare and lost media." },
    { key: "archive", name: "Internet Archive", icon: "\u{1F3DB}", color: "#0f766e", external: true,
      href: "https://archive.org/search?query=rare+footage",
      desc: "The web's memory \u2014 films, audio and books." },
    { key: "flickr", name: "Flickr Commons", icon: "\u25D0", color: "#ff0084", external: true,
      href: "https://www.flickr.com/commons",
      desc: "Rare photographs from public archives." }
  ],

  youtube: [
    { title: "Roundhay Garden Scene (1888) \u2014 restored to 60fps",
      channel: "Denis Shiryaev", year: "1888",
      url: "https://www.youtube.com/watch?v=Fxd8XJ_J0Gc",
      desc: "The oldest surviving film, upscaled frame by frame from just 20 original frames." },
    { title: "The launch of HMS Albion (1898) \u2014 first tragedy ever filmed",
      channel: "Archive", year: "1898",
      url: "https://www.youtube.com/watch?v=Bx4rJCRbnmY",
      desc: "A ship launch that turned fatal, captured by the cameras of the day." },
    { title: "Eisenhower WRC-TV, 1958 \u2014 oldest known colour videotape",
      channel: "Archive", year: "1958",
      url: "https://www.youtube.com/watch?v=QKqHZcXvUAs",
      desc: "A surviving colour videotaping from 1958, when most tape was wiped and reused." },
    { title: "Robert Kennedy watches a Davy Crockett test \u2014 incredibly rare",
      channel: "atomcentral", year: "1962",
      url: "https://www.youtube.com/watch?v=xHiihPD7bLM",
      desc: "Rare 35mm colour negative released under FOIA, showing the smallest nuclear weapon tested." },
    { title: "Rare colour footage of Sarajevo, 1912",
      channel: "Archive", year: "1912",
      url: "https://www.youtube.com/watch?v=WPKmRsHHoUc",
      desc: "Early colour footage of a city on the edge of a century of change." },
    { title: "The Oberg colour film of Pearl Harbor \u2014 7 December 1941",
      channel: "midway51", year: "1941",
      url: "https://www.youtube.com/watch?v=1b6auSQPvGs",
      desc: "Home colour film shot by Harold and Eda Oberg during and after the attack." },
    { title: "Assassination of King Alexander I of Yugoslavia (1934)",
      channel: "British Path\u00e9", year: "1934",
      url: "https://www.youtube.com/watch?v=6R3dVZdFxxo",
      desc: "Newsreel of the first assassination caught on film, from the British Path\u00e9 archive." },
    { title: "1943 raid on Ploesti at tree-top level and back",
      channel: "UnknownWW2InColor", year: "1943",
      url: "https://www.youtube.com/watch?v=6Zk5YeOjYVw",
      desc: "Allied and German footage of the low-level bombing raid on the Romanian oil fields." },
    { title: "The lost 1984 video: Steve Jobs introduces the Macintosh",
      channel: "TextLab", year: "1984",
      url: "https://www.youtube.com/watch?v=2B-XwPjn9YY",
      desc: "Rediscovered in 2004 and restored \u2014 the moment the Macintosh was unveiled." },
    { title: "The Edsel Show (1957) \u2014 oldest videotape recording in existence",
      channel: "kingoftheroad", year: "1957",
      url: "https://www.youtube.com/watch?v=Ze0Az9tdkHg",
      desc: "Bing Crosby, Frank Sinatra and Louis Armstrong on the oldest surviving videotape." }
  ],

  wikipedia: {
    pages: [
      { title: "Lost media", url: "https://en.wikipedia.org/wiki/Lost_media",
        desc: "The umbrella article on media that no longer exists in any known copy." },
      { title: "List of lost films", url: "https://en.wikipedia.org/wiki/List_of_lost_films",
        desc: "A catalogue of films believed to be lost, by decade." },
      { title: "Lost television broadcast", url: "https://en.wikipedia.org/wiki/Lost_television_broadcast",
        desc: "Why so much early television was erased, wiped or never kept." },
      { title: "Roundhay Garden Scene", url: "https://en.wikipedia.org/wiki/Roundhay_Garden_Scene",
        desc: "The 1888 film widely regarded as the oldest surviving motion picture." },
      { title: "List of rediscovered films", url: "https://en.wikipedia.org/wiki/List_of_rediscovered_films",
        desc: "Lost films that were later found \u2014 proof that rare things resurface." },
      { title: "History of photography", url: "https://en.wikipedia.org/wiki/History_of_photography",
        desc: "From heliographs to glass plates: how rare images were first made." }
    ],
    images: [
      { title: "Historical photographs", url: "https://commons.wikimedia.org/wiki/Category:Historical_photographs",
        desc: "Wikimedia Commons category of historical photographs." },
      { title: "19th-century photographs", url: "https://commons.wikimedia.org/wiki/Category:19th-century_photographs",
        desc: "Early photography from the 1800s, free to browse." },
      { title: "Old maps", url: "https://commons.wikimedia.org/wiki/Category:Old_maps",
        desc: "Vintage and historical maps from around the world." },
      { title: "Lantern slides", url: "https://commons.wikimedia.org/wiki/Category:Lantern_slides",
        desc: "Hand-tinted glass slides projected before the age of cinema." },
      { title: "Featured pictures", url: "https://commons.wikimedia.org/wiki/Commons:Featured_pictures",
        desc: "Commons' best images \u2014 a good place to start browsing." },
      { title: "Public domain images", url: "https://commons.wikimedia.org/wiki/Commons:Public_domain",
        desc: "Images free of copyright, safe to reuse and study." }
    ]
  }
};
